const products=[['DRETOSONS NEDI-PE210','220V AC Compact Panel Fan',45],['NMB-7 3610KL','24V DC Low-Noise Precision',52],['Nider BETA-BL 12V','Brushless High-Flow Blower',38],['ebm-papst R9G310','24V High Efficiency Fan',120],['Delta Multi-Stack','Stacked Impeller Module',185],['EC Blower Unit','380V Industrial Centrifugal',210],['High-Flow Axial','IP68 Heavy Fan',145],['Delta Heavy Circular','220V Metal Frame Duct Fan',89],['Double Impeller','48V DC High Pressure Array',165],['Sub-Station Cabinet','12V/24V Industrial Auxiliary',65]];
const pillars={ac:['AC Heavy-Duty Cooling Arrays','Designed for high-voltage panels, transformer units and uninterrupted industrial machinery cooling.',['220V - 380V direct input range','Cast aluminum impeller frames','Maintenance-free dual ball bearings'],'NOMINAL'],dc:['DC & EC Precision Micro-Ventilation','Variable speed PWM control for telecom cabinets, automation racks and battery storage modules.',['12V / 24V / 48V precision inputs','Integrated PWM feedback control','Ultra-quiet acoustic dampening'],'92% EFFICIENCY'],blower:['Industrial Centrifugal Blowers','High static pressure blowers drive dense airflow through restricted ductwork and severe industrial environments.',['High static pressure chamber','IP68 environmental sealing','Reinforced multi-blade turbines'],'850 PA PEAK']};
const $=id=>document.getElementById(id);const fanSelect=$('fanSelect');
products.forEach(([name,desc,price])=>{const option=document.createElement('option');option.value=price;option.dataset.name=name;option.textContent=`${name} ($${price.toFixed(2)})`;fanSelect.appendChild(option);const card=document.createElement('article');card.className='product';card.innerHTML=`<div><div class="product-icon"><i class="fa-solid fa-fan"></i></div><h3>${name}</h3><p>${desc}</p><p class="price">Price: $${price.toFixed(2)}</p></div><button data-product="${name}">SELECT FOR QUOTE</button>`;$('productGrid').appendChild(card)});
function calculate(){const qty=Math.max(1,parseInt($('quantity').value)||1);$('quantity').value=qty;$('total').textContent=`$${((Number(fanSelect.value)||0)+(Number($('accessory').value)||0))*qty.toFixed(2)}`}
fanSelect.addEventListener('change',calculate);$('quantity').addEventListener('input',calculate);$('accessory').addEventListener('change',calculate);document.querySelectorAll('[data-product]').forEach(btn=>btn.addEventListener('click',()=>{fanSelect.value=[...fanSelect.options].findIndex(o=>o.dataset.name===btn.dataset.product);fanSelect.selectedIndex=[...fanSelect.options].findIndex(o=>o.dataset.name===btn.dataset.product);calculate();$('calculator').scrollIntoView({behavior:'smooth'})}));
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');const [title,desc,specs,status]=pillars[tab.dataset.pillar];$('pillarTitle').textContent=title;$('pillarDesc').textContent=desc;$('pillarSpecs').innerHTML=specs.map(s=>`<li>${s}</li>`).join('');$('pillarConsole').textContent=`SYS_PILLAR_CONSOLE v2.4\n> Input signal........ [OK]\n> Mode................ ${tab.dataset.pillar.toUpperCase()}\n> Telemetry............ ${status}`}));
document.querySelectorAll('[data-mode]').forEach(btn=>btn.addEventListener('click',()=>{const time=new Date().toLocaleTimeString();$('telemetryConsole').insertAdjacentHTML('beforeend',`<p>[${time}] ${btn.dataset.mode==='low'?'ECO MODE: 1400 RPM, noise < 28 dBA.':'HIGH PERFORMANCE: 3600 RPM, airflow at 100%.'}</p>`);$('telemetryConsole').scrollTop=$('telemetryConsole').scrollHeight}));
$('quoteForm').addEventListener('submit',e=>{e.preventDefault();const model=fanSelect.options[fanSelect.selectedIndex].dataset.name;const accessory=$('accessory').options[$('accessory').selectedIndex].dataset.name;const message=`Hello DELTA ELECTRIC POWER!\nI would like to place an order/quote request:\n\nModel: ${model}\nQuantity: ${$('quantity').value} unit(s)\nAccessory: ${accessory}\nTotal Estimated Quote: ${$('total').textContent}\n\nPlease confirm availability and dispatch details.`;window.open(`https://wa.me/8801774777962?text=${encodeURIComponent(message)}`,'_blank')});calculate();
