const products=[
  {name:'DRETOSONS NEDI-PE210',desc:'220V AC Compact Panel Fan',price:45,category:'ac',image:'https://res.cloudinary.com/ne7xgr2z/image/upload/f_auto,q_auto/image',alt:'Compact black AC panel cooling fan'},
  {name:'NMB-7 3610KL',desc:'24V DC Low-Noise Precision',price:52,category:'dc',image:'https://res.cloudinary.com/ne7xgr2z/image/upload/f_auto,q_auto/image',alt:'Compact black 24V DC precision fan'},
  {name:'Nider BETA-BL 12V',desc:'Brushless High-Flow Blower',price:38,category:'dc',image:'https://res.cloudinary.com/ne7xgr2z/image/upload/f_auto,q_auto/image',alt:'Compact 12V brushless blower fan'},
  {name:'ebm-papst R9G310',desc:'24V 1.70A High Efficiency',price:120,category:'dc',image:'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80',alt:'Industrial engineering cooling assembly'},
  {name:'Delta Multi-Stack',desc:'Stacked Impeller Module',price:185,category:'blower',image:'https://res.cloudinary.com/ne7xgr2z/image/upload/f_auto,q_auto/image',alt:'Stacked industrial impeller module'},
  {name:'EC Blower Unit',desc:'380V Industrial Centrifugal',price:210,category:'blower',image:'https://res.cloudinary.com/ne7xgr2z/image/upload/f_auto/q_auto/us5lmqze0f3wjegxbqie',alt:'EC centrifugal industrial blower unit'},
  {name:'High-Flow Axial',desc:'IP68 Waterproof Heavy Fan',price:145,category:'ac',image:'https://res.cloudinary.com/ne7xgr2z/image/upload/f_auto/q_auto/a7ojn45hr9qxxmxi355h',alt:'High-flow waterproof axial industrial fan'},
  {name:'Delta Heavy Circular',desc:'220V Metal Frame Duct Fan',price:89,category:'ac',image:'https://res.cloudinary.com/ne7xgr2z/image/upload/f_auto/q_auto/wybvh94nfdklrs6ixb0a',alt:'Heavy circular metal-frame duct fan'},
  {name:'Double Impeller',desc:'48V DC High Pressure Array',price:165,category:'blower',image:'https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?auto=format&fit=crop&w=600&q=80',alt:'Double impeller high-pressure fan assembly'},
  {name:'Sub-Station Cabinet',desc:'12V/24V Industrial Auxiliary',price:65,category:'dc',image:'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80',alt:'Sub-station cabinet cooling fan'}
];
const pillars={ac:['AC Heavy-Duty Cooling Arrays','Designed for high-voltage panel boards, transformer units, and uninterrupted industrial machinery cooling. High airflow output with sustained thermal resilience under continuous load.',['220V - 380V Direct Input Range','Cast Aluminum Impeller Frames','Maintenance-free dual ball bearings'],'MODE: AC_STANDARD','> Telemetry: Nominal 2800 RPM Output'],dc:['DC & EC Precision Micro-Ventilation','Variable speed controls via PWM signals. Ultra-low wattage consumption tailored for precision telecom cabinets, automation logic racks, and battery storage modules.',['12V / 24V / 48V Precision Inputs','Integrated PWM Feedback Control','Ultra-Quiet Acoustic Dampening'],'MODE: DC_EC_PRECISION','> Telemetry: 92% Motor Energy Efficiency'],blower:['Industrial Centrifugal Blowers','High static pressure blowers constructed to drive dense airflow through restricted ductwork, heavy filter assemblies, and severe industrial environments.',['High Static Pressure Chamber','IP68 Environmental Sealing','Reinforced Multi-Blade Turbines'],'MODE: BLOWER_HIGH_PRESS','> Telemetry: Static Pressure Peak 850 Pa']};
const $=id=>document.getElementById(id);const fanSelect=$('fanSelect');
function renderProducts(){fanSelect.innerHTML='';products.forEach(product=>{const option=document.createElement('option');option.value=product.price;option.dataset.name=product.name;option.textContent=`${product.name} ($${product.price.toFixed(2)})`;fanSelect.appendChild(option)});renderCatalog()}
function renderCatalog(){const query=($('productSearch')?.value||'').trim().toLowerCase();const category=$('categoryFilter')?.value||'all';const sort=$('sortProducts')?.value||'featured';let visible=products.filter(product=>(category==='all'||product.category===category)&&(`${product.name} ${product.desc}`.toLowerCase().includes(query)));if(sort==='price-low')visible.sort((a,b)=>a.price-b.price);if(sort==='price-high')visible.sort((a,b)=>b.price-a.price);if(sort==='name')visible.sort((a,b)=>a.name.localeCompare(b.name));$('productGrid').innerHTML=visible.map(product=>`<article class="product-card"><div><div class="card-img"><img src="${product.image}" alt="${product.alt}" loading="lazy" onerror="this.onerror=null;this.src='https://placehold.co/600x600/050509/ffffff?text=DEP+FAN';"><button class="zoom-badge" type="button" aria-label="Zoom ${product.name}" onclick="openZoomModal('${product.image}','${product.name}')"><i class="fa-solid fa-magnifying-glass-plus"></i> ZOOM</button></div><h3>${product.name}</h3><p>${product.desc}</p><p class="price">Price: $${product.price.toFixed(2)}</p></div><button type="button" data-product="${product.name}">SELECT FOR QUOTE</button></article>`).join('');$('catalogStatus').textContent=`Showing ${visible.length} of ${products.length} products`;document.querySelectorAll('[data-product]').forEach(button=>button.addEventListener('click',()=>selectProduct(button.dataset.product)))}
function runCalculation(){const quantity=Math.max(1,parseInt($('quantityInput').value,10)||1);$('quantityInput').value=quantity;const total=((Number(fanSelect.value)||0)+(Number($('accessorySelect').value)||0))*quantity;$('totalPriceDisplay').textContent=`$${total.toFixed(2)}`}
function switchPillar(type){const data=pillars[type];if(!data)return;document.querySelectorAll('.pillar-btn').forEach(button=>button.classList.remove('active'));$(`tab-${type}`).classList.add('active');$('pillarTitle').textContent=data[0];$('pillarDesc').textContent=data[1];$('pillarSpecs').innerHTML=data[2].map(item=>`<li>${item}</li>`).join('');$('pillarConsole').textContent=`SYS_PILLAR_CONSOLE v2.4\n> Checking Input Signal... [OK]\n> Frequency: 50Hz/60Hz Sync Verified\n> Thermal Limit: < 85°C Operational\n> ${data[4]}`}
function selectProduct(name){const index=[...fanSelect.options].findIndex(option=>option.dataset.name===name);if(index>=0){fanSelect.selectedIndex=index;runCalculation();$('calculator').scrollIntoView({behavior:'smooth',block:'start'})}}
function adjustFanSpeed(mode){const box=$('telemetryConsole');const time=new Date().toLocaleTimeString();box.insertAdjacentHTML('beforeend',`<p>[${time}] ${mode==='low'?'ECO MODE ACTIVATED: Voltage scaled to 60%. RPM throttled to 1400. Noise < 28 dBA.':'HIGH PERFORMANCE ENGAGED: Max voltage applied. RPM boosted to 3600. Airflow at 100% capacity.'}</p>`);box.scrollTop=box.scrollHeight}
function toggleNosFeature(input){const box=$('telemetryConsole');const time=new Date().toLocaleTimeString();box.insertAdjacentHTML('beforeend',`<p>[${time}] NOS BOOST MODE: ${input.checked?'Standby protocol loaded. Feature module active.':'Deactivated.'}</p>`);box.scrollTop=box.scrollHeight}
function handleOrderSubmission(event){event.preventDefault();const model=fanSelect.options[fanSelect.selectedIndex].dataset.name;const accessory=$('accessorySelect').options[$('accessorySelect').selectedIndex].dataset.acc;const message=`Hello DELTA ELECTRIC POWER!\nI would like to place an order/quote request:\n\n*Model:* ${model}\n*Quantity:* ${$('quantityInput').value} unit(s)\n*Accessory:* ${accessory}\n*Total Estimated Quote:* ${$('totalPriceDisplay').textContent}\n\nPlease confirm availability and dispatch details.`;window.open(`https://wa.me/8801774777962?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')}
function openZoomModal(image,title){$('modalImg').src=image;$('modalImg').alt=title;$('modalTitle').textContent=title;$('imageModal').classList.remove('hidden')}function closeZoomModal(){$('imageModal').classList.add('hidden')}function toggleImageZoom(container){container.querySelector('img').classList.toggle('scale-150')}
window.addEventListener('DOMContentLoaded',()=>{renderProducts();fanSelect.addEventListener('change',runCalculation);$('quantityInput').addEventListener('input',runCalculation);$('accessorySelect').addEventListener('change',runCalculation);$('productSearch').addEventListener('input',renderCatalog);$('categoryFilter').addEventListener('change',renderCatalog);$('sortProducts').addEventListener('change',renderCatalog);runCalculation()});
